---
title: "LC-MS/MS Raw Files report"
output: pdf_document
params:
  RAW : NA
  table_names: NA
  RAW_irt: NA
  irt_peptides_check: NA
  number_cores: NA

---


```{r, results='asis', echo=FALSE}

knitr::kable(params$table_names, format = 'markdown')
```
\newpage

```{r, echo=FALSE}
iRT.mZ <- c(487.2571, 547.2984, 622.8539, 636.8695, 644.8230, 669.8384,
            683.8282, 683.8541, 699.3388, 726.8361, 776.9301)

iRT.score <- c(-24.92, 19.79, 70.52, 87.23, 0, 28.71, 12.39, 33.38, 42.26,
               54.62, 100)

names(iRT.mZ) <- c("LGGNEQVTR", "YILAGVENSK", "GTFIIDPGGVIR", "GTFIIDPAAVIR",
                   "GAGSSEPVTGLDAK", "TPVISGGPYEYR", "VEATFGVDESNAK",
                   "TPVITGAPYEYR", "DGLDAASYYAPVR", "ADVTPADFSEWSK",
                   "LFLQFGAQGSPFLK")
```

```{r, echo=FALSE}


.getInstrumentInformation <- function(x){data.frame(model=x$`Instrument model`,
                                                     serialNumber=x$`Serial number`,
                                                     #method=x$`Instrument method`,
                                                     softwareVersion=x$`Software version`,
                                                     nMS=x$`Number of scans`,
                                                     nMS2=x$`Number of ms2 scans`)
                                        }



.plotChromatogramAndFit <-  function(x, i, ...){
    par(mfrow=c(2,1))

    plot(x, ...); legend("topright", legend=i, title='Instrument Model', bty = "n", cex=0.75)

    rt <- sapply(x, function(x) x$times[which.max(x$intensities)[1]])
    if (length(rt) == length(iRT.score)){
    fit <- lm(rt ~ iRT.score)
    plot(rt ~ iRT.score, ylab = 'Retention time [min]',
         xlab = "iRT score", pch=16, frame.plot = FALSE, ...)
    abline(fit, col = 'grey')
    abline(v = 0, col = "grey", lty = 2)
    legend("topleft",
     legend = paste("Regression line: ", "rt =",
                    format(coef(fit)[1], digits = 4), " + ",
                    format(coef(fit)[2], digits = 2), "score", "\nR2: ",
                    format(summary(fit)$r.squared, digits = 2)),
           bty = "n", cex = 0.75)
    text(iRT.score, rt,  iRT.mZ,pos=1,cex=0.5)
    }
}






```



```{r ,echo=FALSE, fig.height=8}
if (params$irt_peptides_check==TRUE){


    
H <- mclapply(FUN=rawrr::readFileHeader, params$RAW_irt, mc.cores = params$number_cores)



instrumentInformation <- do.call('rbind',lapply(H, .getInstrumentInformation))

C <- mclapply(X = params$RAW_irt,
              FUN = rawrr::readChromatogram,
              mass = iRT.mZ,
              tol = 10,
              type = "xic",
              filter = "ms", 
              mc.cores = params$number_cores)


rv <- mapply(FUN=.plotChromatogramAndFit,
             x=C, i=instrumentInformation$model, main=basename(params$RAW_irt))
  
  
}
```


\newpage
```{r, echo=FALSE, fig.height=8}

print(PlotInjectionTime(params$RAW))
```

\newpage

```{r, echo=FALSE, fig.height=8}
print(PlotMzDistribution(params$RAW))
```

\newpage

```{r, results='asis', fig.height=8}

print(PlotCycleTime(params$RAW))


```

\newpage

```{r, echo=FALSE,results='asis',fig.height=8 }

print(PlotScanTime(params$RAW))


```

\newpage

```{r, echo=FALSE,results='asis', fig.height=8}
print(PlotChargeState(params$RAW))


```

\newpage

```{r,echo=FALSE, results='asis', fig.height=8}

print(PlotTicBasepeak(params$RAW))



```

